### ISSUE TITLE
This is at least one of the issues

### ISSUE THREAD

**Issue by ztbrown** [schmonz/qmail#1]
https://github.com/schmonz/qmail/blob/23977bb1fb2808097922c8862efba6b1c29a843e/qmail-fixsmtpio.c#L467

The problem I was having here was `get_next_field` was returning an empty character array when it should have returned NULL. 

I changed the line to deal with the case when the stralloc line looks like this`AUTHUSER:timeout::*:16:`, the `start` int is 23 and the stralloc length is 24. 

Here is the change I made: 

```c
if((str_len(temp) > 0) && (line->s[i] == ':' || i == line->len - 1)) {
```

**Comment by schmonz** [comment]
I'm extremely willing to believe there's at least one bug in that line, and when I make your change the program stops segfaulting (OS X 10.13.1, clang 900.0.38, default `conf-cc` and `conf-ld`) on startup, so the filter rule probably loaded. Instead, it segfaults on timeout, presumably when attempting to match or apply the rule.

`str_len()` doesn't make sense on `temp`, because that's a `stralloc` and the expected argument is a C string. I guess it helps because the struct hasn't had anything written to it since it was initialized with zero? When I change `str_len(temp)` to `temp.len`, the segfault on startup returns.

Maybe you have tests that helped you find this? I've granted you push access. :-)

**Comment by schmonz** [comment]
I’ve since deleted the config parser in favor of hardcoded rules while I establish test coverage and Valgrind happiness. Once I’ve got enough confidence, I’ll test-drive a config parser. I plan to close this bug when I’ve done that. Let me know if you’ll want to play along.

**Comment by schmonz** [comment]
I've finally shipped it! Check it out: https://schmonz.com/qmail/acceptutils

Thanks again for your help, mang!
